version: '3.8'
services:
  eurekaserver:
    image: kds.inveniacorp.com/dev/msa-base/eureka-server:latest
    restart: on-failure
    ports:
      - "8761:8761"
    networks:
      - msa
    environment:
      TZ: "Asia/Seoul"
    build:
      context: ./eureka-server

  configserver:
    image: kds.inveniacorp.com/dev/msa-base/config-server:latest
    restart: on-failure
    ports:
      - "8888:8888"
    networks:
      - msa
    environment:
      TZ: "Asia/Seoul"
      RABBITMQ_HOST: "rabbitmq"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      ENCRYPT_KEY: "damu"
    build:
      context: ./config-server
    depends_on:
      - eurekaserver

  apigateway:
    image: kds.inveniacorp.com/dev/msa-base/api-gateway:latest
    restart: on-failure
    networks:
      - msa
    environment:
      TZ: "Asia/Seoul"
      RABBITMQ_HOST: "rabbitmq"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      ENCRYPT_KEY: "damu"
      CONFIGSERVER_URI: "http://configserver:8888"
    build:
      context: ./api-gateway
    depends_on:
      - eurekaserver
      - configserver
    extra_hosts:
      - "sso.inveniacorp.com: 100.100.16.178"

networks:
  msa:
    external: true
    name: msa
