# Default settings

---
# Development settings
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:Altibase://100.100.10.72:10003/mydb"
    driver-class-name: "Altibase.jdbc.driver.AltibaseDriver"
    username: "g2"
    password: "{cipher}8437ea7b287ebba1eea255d24edf2164a27e1d7bb7882cddecf40c7fea4720ec"
---
# Product settings
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: "jdbc:Altibase://100.100.10.143:20300/mydb"
    driver-class-name: "Altibase.jdbc.driver.AltibaseDriver"
    username: "g2"
    password: "{cipher}8437ea7b287ebba1eea255d24edf2164a27e1d7bb7882cddecf40c7fea4720ec"
test:
  version: test1
