version: '3.8'
services:
  keycloak:
    image: kds.inveniacorp.com/dev/keycloak-theme/keycloak:latest
    restart: on-failure
    networks:
      - msa
    environment:
      TZ: "Asia/Seoul"
      # Admin account
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: "https://sso.inveniacorp.com/auth/"
      PROXY_ADDRESS_FORWARDING: "true"
      # DB
      DB_VENDOR: mariadb
      DB_ADDR: 100.100.10.177
      DB_PORT: 3306
      DB_DATABASE: keycloak_dev
      DB_USER: e1264
      DB_PASSWORD: inveni@2020
    command:
      - "-b"
      - "0.0.0.0"

networks:
  msa:
    external: true
    name: msa
