version: '3.8'
services:
  keycloak:
    image: zmmx011/keycloak-theme:latest
    restart: on-failure
    ports:
      - "4080:8080"
    networks:
      - msa
    environment:
      TZ: "Asia/Seoul"
      # Admin account
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: "https://sso.inveniacorp.com:8080/auth/"
      PROXY_ADDRESS_FORWARDING: "true"
      # DB
      DB_VENDOR: mariadb
      DB_ADDR: 100.100.10.177
      DB_PORT: 3306
      DB_DATABASE: keycloak_dev
      DB_USER: e1264
      DB_PASSWORD: inveni@2020
    volumes:
      - /data/nfs/keycloak-theme:/opt/jboss/keycloak/themes/keycloak-theme
    command:
      - "-b"
      - "0.0.0.0"

networks:
  msa:
    external: true
    name: msa
