version: '3.8'

services:
  nginx:
    image: kds.inveniacorp.com/dev/config-repo/dmz-web:latest
    ports:
      - "80:80"
      - "443:443"
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
