# Default settings
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:mariadb://100.100.10.177:3306/INVENIA_DEV?characterEncoding=UTF-8"
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: "e1264"
    password: "{cipher}09c495e08d694d4a875c33eb662425fb8017b268a823f99c69342fb7625b6a78"
example:
  profile: "Current profile is default"

---
# Development settings
spring:
  config:
    activate:
      on-profile: dev
example:
  profile: "Current profile is dev"
---
# Product settings
spring:
  config:
    activate:
      on-profile: prod
example:
  profile: "Current profile is prod"
