# Development settings
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:mariadb://100.100.10.177:3306/invenia_erp"
    username: "e1264"
    password: "{cipher}cff26331e887aff119cd77b6c5acc52d60d1d42bf73e2c0e7362a6faa17a4df4"
---
# Product settings
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: "jdbc:mariadb://100.100.10.177:3306/invenia_erp"
    username: "e1264"
    password: "{cipher}cff26331e887aff119cd77b6c5acc52d60d1d42bf73e2c0e7362a6faa17a4df4"
