version: '3.8'

services:
  nginx:
    image: kds.inveniacorp.com/dev/config-repo/internal-web:latest
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "8080:8080"
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    networks:
      - msa
networks:
  msa:
    external: true
    name: msa
