version: '3.8'

services:
  nginx:
    image: kds.inveniacorp.com/dev/internal-web/internal-web:latest
    volumes:
      - "/var/lib/docker/volumes/nginx/logs:/logs"
    ports:
      - target: 443
        published: 443
        protocol: tcp
      - target: 8000
        published: 8000
        protocol: tcp
      - target: 8080
        published: 8080
        protocol: tcp
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    networks:
      - msa
networks:
  msa:
    external: true
    name: msa
