version: '3.8'
services:
  erpservice:
    image: kds.inveniacorp.com/dev/erp-service/erp-service:latest
    restart: on-failure
    ports:
      - "8010:8010"
    environment:
      TZ: "Asia/Seoul"
      RABBITMQ_HOST: "rabbitmq"
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: "8010"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
      ENCRYPT_KEY: "damu"
    volumes:
      - /data/erp-service/java.security:/opt/openjdk-17/conf/security/java.security
      - /data/erp-service/java.security:/etc/alternatives/jre/lib/security/java.security
    build:
      context: .
    networks:
      - msa
networks:
  msa:
    external: true
    name: msa
