# Default settings
spring:
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: "jdbc:sqlserver://100.100.10.72:10002;database=INVENIA"
    driver-class-name: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    username: "genuine"
    password: "{cipher}0ca73e5fe38d5bcef4faaa4a8e76ec262d18273e3e6b846cc9009490f70ebe2f"
example:
  profile: "Current profile is default"

---
# Development settings
spring:
  config:
    activate:
      on-profile: dev
example:
  profile: "Current profile is dev"
---
# Product settings
spring:
  config:
    activate:
      on-profile: prod
example:
  profile: "Current profile is prod"
