# Default settings
spring:
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: "jdbc:mariadb://100.100.10.177:3306/INVENIA_DEV?characterEncoding=UTF-8"
    driver-class-name: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    username: "e1264"
    password: "inveni@2020"
example:
  profile: "Current profile is default"

---
# Development settings
spring:
  config:
    activate:
      on-profile: dev
example:
  profile: "Current profile is dev"
---
# Product settings
spring:
  config:
    activate:
      on-profile: prod
example:
  profile: "Current profile is prod"
