# Development settings
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: "jdbc:mariadb://100.100.10.177:3306/invenia_erp"
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: "e1264"
    password: "{cipher}cff26331e887aff119cd77b6c5acc52d60d1d42bf73e2c0e7362a6faa17a4df4"
keycloak:
  auth-server-url: "https://sso.inveniacorp.com:8080/auth"
  realm: "service"
  client-id: "admin-cli"
  client-secret: "GefnvC2flJEwe8FIm1YjreTjVZKQEFFb"
test:
  name: rabbitmq
---
# Product settings
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: "jdbc:mariadb://100.100.10.177:3306/invenia_erp"
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: "e1264"
    password: "{cipher}cff26331e887aff119cd77b6c5acc52d60d1d42bf73e2c0e7362a6faa17a4df4"
keycloak:
  auth-server-url: "http://100.100.10.174:4080/auth"
  realm: "service"
  client-id: "admin-cli"
  client-secret: "GefnvC2flJEwe8FIm1YjreTjVZKQEFFb"
