# Default settings

---
# Development settings
spring:
  config:
    activate:
      on-profile: dev
---
# Product settings
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: "jdbc:sqlserver://100.100.10.192:14233;database=INVENIATEST"
    driver-class-name: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    username: "genuine"
    password: "{cipher}0ca73e5fe38d5bcef4faaa4a8e76ec262d18273e3e6b846cc9009490f70ebe2f"
